---
- name: User creator
  hosts: all
  become: true
  vars_prompt:
    - name: password
      prompt: "Enter a password for the user {{ user }}"
      private: true
      encrypt: "md5_crypt"
      confirm: true
      salt_size: 7

  tasks:
    - name: Create user
      ansible.builtin.user:
        user: "{{user}}"
        create_home: true
        groups: "{{ groups_var }}"
        append: true
        shell: /bin/bash

    - name: Add authorized key
      ansible.posix.authorized_key:
        user: "{{user}}"
        key: "{{key_var}}"

    - name: Set password for {{ user }}
      ansible.builtin.user:
        user: "{{user}}"
        password: "{{password}}"
        update_password: on_create